### ISSUE TITLE
哈喽，你好。有个问题请教一下。验证那里验证字段长度 obj.conditions[0]这个是什么意思呢。看得有点懵 哈哈哈初学者

### ISSUE THREAD

**Issue by crismcn** [2017coding/BBS_node#1]
length: obj => {
          if (!obj.value) return true
          return obj.conditions[0] <= obj.value.length && obj.value.length <= obj.conditions[1]
        },

**Comment by 2017coding** [comment]
不好意思，现在才看到
*  @param {Array} conditions: 条件字段 例如： ['2', '10'] ,则验证长度错误会提示: 密码的长度在2到10个字符
自定义的规则，当验证length时，条件就是长度，代码里这样写的确实不好理解
